# Generated by Django 5.2.4 on 2025-07-07 16:05

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/Caracas'),
        ),
    ]
